name: New Version

on:
  workflow_dispatch:

jobs:
  publish-npm:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 15
      - run: npm i -f
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./packages/gatsby-theme-chronoblog/package.json
          token: ${{ secrets.NPM_TOKEN }}
