name: New Push

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 220
    name: Test ${{ matrix.starter_folder }} on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [15]
        os: [ubuntu-latest, macos-latest, windows-latest]
        starter_folder:
          [
            examples/chronoblog-netlify-cms,
            starters/chronoblog,
            starters/hacker,
            starters/profile,
            test-builds/content-tests,
            test-builds/chinese-language-test,
            test-builds/profile-minimal,
          ]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm i
      - run: npm run generate-starters
      - run: npm i
      - run: cd ${{ matrix.starter_folder }} && npm run build

  publish-npm:
    needs: [tests]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 15
      - run: npm i
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./packages/gatsby-theme-chronoblog/package.json
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

  publish-starters:
    needs: [tests]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Publish Starters Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Publish Starters
          token: ${{ secrets.API_TOKEN_GITHUB }}
          inputs: '{ "type": "all" }'
