name: Publish Starters

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Type"
        required: true
        # all | examples | starters
        default: "examples"

jobs:
  publish-examples:
    if: ${{ github.event.inputs.type == 'examples' || github.event.inputs.type == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [chronoblog-netlify-cms]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 15
      - run: npm i
      - run: npm run generate-starters

      - name: Copy directory examples/${{ matrix.example }}/. to gatsby-starter-${{ matrix.example }} repository
      - run: npm i
      - run: npm run generate-starters
        uses: andstor/copycat-action@v3.2.3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: examples/${{ matrix.example }}/.
          dst_path: /.
          clean: true
          dst_owner: Chronoblog
          dst_repo_name: gatsby-starter-${{ matrix.example }}

  publish-starters:
    if: ${{ github.event.inputs.type == 'starters' || github.event.inputs.type == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        starter: [chronoblog, chronoblog-hacker, chronoblog-profile]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 15
      - run: npm i
      - run: npm run generate-starters

      - name: Copy directory starters/${{ matrix.starter }}/. to gatsby-starter-${{ matrix.starter }} repository
        uses: andstor/copycat-action@v3.2.3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: starters/${{ matrix.starter }}/.
          dst_path: /.
          clean: true
          dst_owner: Chronoblog
          dst_repo_name: gatsby-starter-${{ matrix.starter }}
