name: Publish Starters

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Type can be: all | examples | starters"
        required: true
        # all | examples | starters
        default: "examples"

jobs:
  publish-examples:
    if: ${{ github.event.inputs.type == 'examples' || github.event.inputs.type == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [chronoblog-netlify-cms]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 15
      - run: npm i
      - run: npm run generate-starters
      - run: chmod 746 ./examples/chronoblog-netlify-cms/.eslintrc.json
      - name: Push "examples/${{ matrix.example }}" to "gatsby-starter-${{ matrix.example }}" repo
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "examples/${{ matrix.example }}"
          destination-github-username: "Chronoblog"
          destination-repository-name: "gatsby-starter-${{ matrix.example }}"
          user-email: 8168280+Ganevru@users.noreply.github.com

  publish-starters:
    if: ${{ github.event.inputs.type == 'starters' || github.event.inputs.type == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        starter: [chronoblog, chronoblog-hacker, chronoblog-profile]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 15
      - run: npm i
      - run: npm run generate-starters
      - name: Push "starters/${{ matrix.starter }}" to "gatsby-starter-${{ matrix.starter }}" repo
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "starters/${{ matrix.starter }}"
          destination-github-username: "Chronoblog"
          destination-repository-name: "gatsby-starter-${{ matrix.starter }}"
          user-email: 8168280+Ganevru@users.noreply.github.com
