name: Test and Publish Starters
on:
  push:
    tags:
      - "*@*"
jobs:
  tests:
    timeout-minutes: 220
    name: Test Starter ${{ matrix.starter }} on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12]
        os: [ubuntu-latest, macos-latest, windows-latest]
        starter:
          [
            chronoblog,
            chronoblog-netlify-cms,
            chronoblog-disqus,
            minimal,
            profile,
            hacker,
          ]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: starter ${{ matrix.starter }}
        run: |
          cd starters/${{ matrix.starter }}/
          echo $PWD
          npm install
          npm run build

  publish:
    timeout-minutes: 220
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: publish:starters
        uses: johno/actions-push-subdirectories@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: starters Chronoblog starter-name
