name: Publication of Starters

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "examples/chronoblog-netlify-cms"
          destination-github-username: "Ganevru"
          destination-repository-name: "gatsby-starter-chronoblog-netlify-cms"
          user-email: 8168280+Ganevru@users.noreply.github.com
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
