name: Tests and Publish
on: [push]
jobs:
  tests:
    timeout-minutes: 220
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: yarn install
        run: yarn install

      - name: yarn test
        run: yarn test

      - name: yarn build:chronoblog
        run: yarn build:chronoblog

      - name: yarn build:chronoblog-netlify-cms
        run: yarn build:chronoblog-netlify-cms

      - name: yarn build:chronoblog-disqus
        run: yarn build:chronoblog-disqus

      - name: yarn build:minimal
        run: yarn build:minimal

      - name: yarn build:content-tests
        run: yarn build:content-tests

      - name: yarn build:profile-minimal
        run: yarn build:profile-minimal

      - name: yarn build:profile
        run: yarn build:profile

      - name: yarn build:hacker
        run: yarn build:hacker
  publish-examples:
    needs: tests
    if: github.event.ref_type == 'tag'
    timeout-minutes: 220
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: publish:examples
        uses: johno/actions-push-subdirectories@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: examples Chronoblog starter-name
  publish-startest:
    needs: tests
    if: github.event.ref_type == 'tag'
    timeout-minutes: 220
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: publish:starters
        uses: johno/actions-push-subdirectories@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: starters Chronoblog starter-name
